### ISSUE TITLE
compilation scripts

### ISSUE THREAD

**Issue by lorenzhs** [Poyias/mBonsai#1]
- `-O6` does nothing more than `-O3`. There is `-Ofast` which does some non-standard-compliant optimizations on top of `-O3`
- you can use the shell variable `${HOME}` instead of `/home/"USERNAME"` and save the user some trouble

**Comment by Poyias** [comment]
Thank you for the feedback Lorenz.

Fixed .sh.
I really appreciate it, even though under the same supervisor we never had
the chance to meet properly.

I hope you like mBonsai or Bonsai implementation.
Any feedback is welcome.
I will definetely be improving it in the future.

Best
Andreas

**Comment by lorenzhs** [comment]
:+1: cool!
